environments:
  develop:
    values:
      - domain: dev.192.168.56.120.nip.io
  production:
    values:
      - domain: 192.168.56.120.xip.io

repositories:
- name: stable
  url: https://charts.helm.sh/stable
- name: harbor
  url: https://helm.goharbor.io

templates:
  template: &template
    missingFileHandler: Info
    values:
    - ./values/{{`{{ .Release.Name }}`}}.yaml.gotmpl

releases:
- name: nginx-ingress
  chart: stable/nginx-ingress
  namespace: nginx-ingress
  version: 1.41.3
  <<: *template

- name: harbor
  chart: harbor/harbor
  namespace: harbor
  version: 1.4.2
  <<: *template